<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<h2>
    <span>
        <a href="#">
             <img alt="" src="<?php echo $this->getSkinUrl('images/more.png'); ?>">
        </a>
    </span>
    <?php echo $this->getTitle() ?>
</h2>
<?php $i=0; foreach ($_productCollection as $_product): ?>

<div class="col-xs-6 col-sm-3">
    <a class="IMG" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt=""></a>
    <a class="wenzi" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
</div>

<?php endforeach ?>
