<?php $_productCollection=$this->getLoadedProductCollection(); $_helper = $this->helper('catalog/output'); ?>

<h2>
    <span>
        <a href="#">
                <img alt="" src="<?php echo $this->getSkinUrl('images/more.png'); ?>">
            </a>
    </span>
    <?php echo $this->getTitle() ?>
</h2>
<?php $i=0; foreach ($_productCollection as $_product): ?>
<div class="col-xs-6 col-sm-3">
    <a class="IMG" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt=""></a>
    <div class="bottom">
        <b title="分享数">
              <?php echo rand(0,1000)?>人喜欢
           </b>
        <span class="J_card fr">
            <?php echo Mage::helper( 'core')->currency($_product->getPrice(), true, false);?>
        </span>
    </div>
    <div class="follow followbox">
        <h4>
            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
    </div>
</div>


<?php endforeach ?>
