<?php /** * Magento responsive theme * * @category design * @package bootstrapped_default * @copyright Copyright (c) 2012 Magenthon (http://magenthon.com) * @license http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0) * @author Vedran Subotic <vedran@magenthon.com>*/ /** * Product view template * * @see Mage_Catalog_Block_Product_View * @see Mage_Review_Block_Product_View */ ?>
<?php $_helper=$this->helper('catalog/output'); ?>
<?php $_product=$this->getProduct(); ?>
<script type="text/javascript">
var optionsPrice = new Product.OptionsPrice( <?php echo $this -> getJsonConfig() ?> );
</script>

<div class="row detail">

    <div id="messages_product_view">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="col-sm-4">
        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
            <p>
                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></p>
        </div>
    </div>
    <div class="col-md-5">
        <div class="product-shop">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form" <?php if($_product->getOptions()): ?> enctype="multipart/form-data"
                <?php endif; ?>class="form">
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>

                <?php echo $this->getTierPriceHtml() ?>

                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                <div class="price-box">
                    <?php if($_product->isSaleable()): ?>
                    <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                </div>
                <?php echo $this->getChildHtml('addto') ?>
                <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$_product->isSaleable()): ?>
                <div class="price-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php endif; ?>
             
                <div class="price-box">
                    <span>支付方式：</span>
                    <img src="http://www.mintaicorp.com/skin/frontend/default/se101/images/payment-options.gif">
                </div>
                <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2>
                        <?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std">
                        <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
                <?php endif;?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
        </div>

        </form>
        <script type="text/javascript">
        //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                    form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {}
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url) {
            if (this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
         //]]>
        </script>
    </div>
</div>
<div class="product-collateral">
        <div class="product-collateral-left ui-tabs ui-widget ui-widget-content ui-corner-all" id="tabs">
              <ul role="tablist" id="bg" class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
                <li id="one1" onclick="setTab('one',1)" aria-selected="false" aria-labelledby="ui-id-1" aria-controls="tabs-1" tabindex="-1" role="tab" class="ui-state-default ui-corner-top ui-state-active"> <a href="#tabs-1">
                        <?php echo $this->__('description');?></a></li>
                <li id="one2" onclick="setTab('one',2)" aria-selected="false" aria-labelledby="ui-id-2" aria-controls="tabs-2" tabindex="-1" role="tab" class="ui-state-default ui-corner-top"> <a href="#tabs-2">
                        <?php echo $this->__('review');?></a></li>
                <li id="one3" onclick="setTab('one',3)" aria-selected="true" aria-labelledby="ui-id-3" aria-controls="tabs-3" tabindex="0" role="tab" class="ui-state-default ui-corner-top ui-tabs-active"><a href="#tabs-3">
                        <?php echo $this->__('month order review');?></a></li>
              </ul>
              <div style="display:block" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-box" id="con_one_1"> 
              	 <?php echo $_product->getDescription();?>
                <?php echo $this->getChildHtml('product.info.product_additional_data') ?>
              </div>
                <div aria-hidden="true" aria-expanded="false" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-box" aria-labelledby="ui-id-2" id="con_one_2">
               <?php echo $this->getChildHtml('product_review') ?>
                </div>
                <div aria-hidden="false" aria-expanded="true" role="tabpanel" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-box" aria-labelledby="ui-id-3" id="con_one_3">
                    <?php echo $this->getLayout()->createBlock('magemenu/orders')->assign('productname', $_product->getName())->setTemplate('catalog/product/view/orders.phtml')->toHtml(); ?>
                </div>
            </div>         
        </div>
	<script type="text/javascript">
	   function setTab(name,cursel){
		cursel_0=cursel;
		var links = document.getElementById("tabs").getElementsByTagName('li')
		links_len=links.length;
		for(var i=1; i<=links_len; i++){
			var menu = document.getElementById(name+i);
			var id_value = "con_"+name+"_"+i;
			var menudiv = document.getElementById("con_"+name+"_"+i);
			if(i==cursel){
				menu.className="ui-state-default ui-corner-top ui-state-active";
				menudiv.style.display="block";
			}
			else{
				menu.className="ui-state-default ui-corner-top";
				menudiv.style.display="none";
			}
		}
	  }
	  function Next(){                                                        
		cursel_0++;
		if (cursel_0>links_len)cursel_0=1
		setTab(name_0,cursel_0);
	} 
	</script>