<table border="0" cellspacing="0" cellpadding="0"
	server-num="malldetailskip010096058087.cm3" class="table-deal-record"
	summary="成交记录">
	<caption class="month-record">
		本商品累计售出<em class="count">451</em>件 ，最近一个月成交<em>424</em>件
	</caption>
	<colgroup>
		<col class="col-buyer">
		<col class="col-goods">
		<col class="col-price">
		<col class="col-amount">
		<col class="col-chargetime">
		<col class="col-status">
	</colgroup>
	<tbody>
		<tr>
			<th>买家<span class="tb-anonytip">[登录后可见]</span></th>
			<th>宝贝名称</th>
			<th>价格</th>
			<th>购买数量</th>
			<th>成交时间</th>
			<th>状态</th>
		</tr>
		<tr>
			<td class="cell-align-l">l<span class="tb-anonymous">**</span>g <img
				border="0" align="absmiddle" class="rank" title="11－40个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_2.gif">
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-03 11:13:16</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">杨<span class="tb-anonymous">**</span>7 <img
				border="0" align="absmiddle" class="rank" title="251－500个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_1.gif"> <a
				title="V3会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V3会员"
					src="http://gi1.md.alicdn.com/tps/i1/T1GYuIXcRkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-03 11:02:56</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">指<span class="tb-anonymous">**</span>离 <img
				border="0" align="absmiddle" class="rank" title="251－500个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_1.gif"> <a
				title="V3会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V3会员"
					src="http://gi1.md.alicdn.com/tps/i1/T1GYuIXcRkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 23:07:53</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">宝<span class="tb-anonymous">**</span>吗 <img
				border="0" align="absmiddle" class="rank" title="41－90个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_3.gif"> <a title="V1会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V1会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1PbuIXclkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 22:33:56</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">t<span class="tb-anonymous">**</span>1 <img
				border="0" align="absmiddle" class="rank" title="11－40个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_2.gif">
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 22:03:52</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">林<span class="tb-anonymous">**</span>q <img
				border="0" align="absmiddle" class="rank" title="251－500个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_1.gif"> <a
				title="V5会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V5会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1GbuIXcNkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 20:50:54</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">张<span class="tb-anonymous">**</span>1 <img
				border="0" align="absmiddle" class="rank" title="11－40个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_2.gif">
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 20:16:30</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">t<span class="tb-anonymous">**</span>0 <img
				border="0" align="absmiddle" class="rank" title="11－40个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_2.gif"> <a title="V1会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V1会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1PbuIXclkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 20:13:41</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">凌<span class="tb-anonymous">**</span>5 <img
				border="0" align="absmiddle" class="rank" title="41－90个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_3.gif"> <a title="V2会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V2会员"
					src="http://gi4.md.alicdn.com/tps/i4/T1FHuIXcNkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 19:15:48</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">p<span class="tb-anonymous">**</span>2 <img
				border="0" align="absmiddle" class="rank" title="251－500个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_1.gif"> <a
				title="V3会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V3会员"
					src="http://gi1.md.alicdn.com/tps/i1/T1GYuIXcRkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 19:10:03</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">h<span class="tb-anonymous">**</span>1 <img
				border="0" align="absmiddle" class="rank" title="11－40个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_2.gif"> <a title="V1会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V1会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1PbuIXclkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 18:47:30</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">妩<span class="tb-anonymous">**</span>2 <img
				border="0" align="absmiddle" class="rank" title="41－90个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_3.gif"> <a title="V2会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V2会员"
					src="http://gi4.md.alicdn.com/tps/i4/T1FHuIXcNkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 18:30:41</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">j<span class="tb-anonymous">**</span>4 <img
				border="0" align="absmiddle" class="rank" title="251－500个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_1.gif"> <a
				title="V1会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V1会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1PbuIXclkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 17:43:43</td>
			<td>成交</td>
		</tr>
		<tr class="odd">
			<td class="cell-align-l">麦<span class="tb-anonymous">**</span>萍 <img
				border="0" align="absmiddle" class="rank" title="41－90个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_red_3.gif"> <a title="V1会员"
				href="http://vip.taobao.com" target="_blank"><img alt="V1会员"
					src="http://gi3.md.alicdn.com/tps/i3/T1PbuIXclkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><a class="tm-buy-prom" target="_blank"
				href="http://www.tmall.com/go/act/sale/sjzxj.php">手机专享</a></td>
			<td>1</td>
			<td>2014-04-02 16:00:49</td>
			<td>成交</td>
		</tr>
		<tr>
			<td class="cell-align-l">幻<span class="tb-anonymous">**</span>易 <img
				border="0" align="absmiddle" class="rank" title="1001－2000个买家信用积分"
				src="http://pics.taobaocdn.com/newrank/b_blue_3.gif"> <a
				title="V4会员" href="http://vip.taobao.com" target="_blank"><img
					alt="V4会员"
					src="http://gi2.md.alicdn.com/tps/i2/T1HbuIXcNkXXXXXXXX-16-16.png"></a>
			</td>
			<td class="cell-align-l">2014年春夏新款 TEMIX畅销10瓶套装6ML 光泽持久指甲油 美甲正品 <br>
			</td>
			<td><em>24</em> <a class="buyer-cu-icon" title="活动促销 "></a></td>
			<td>1</td>
			<td>2014-04-02 15:37:11</td>
			<td>成交</td>
		</tr>
	</tbody>
</table>