<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<div class="list list2">
	<h2>
		<?php echo $this->getTitle() ?>
	</h2>
	<ul>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		<li><a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" /></a>
			<div class="bottom">
				<b> <?php echo rand(0,1000).$this->__('Shares')?> </b> <span class="J_card fr"> <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false);?> </span>
			</div>
			<div class="follow followbox">
				<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
			</div>
		</li>
		<?php endforeach ?>
	</ul>
</div>