	<?php
		function cut_string($string,$number){
			if(strlen($string) <= $number) {
				return $string;
			}
			else {	
				if(strpos($string," ",$number) > $number){
					$new_space = strpos($string," ",$number);
					$new_string = substr($string,0,$new_space)."..";
					return $new_string;
				}
				$new_string = substr($string,0,$number)."..";
				return $new_string;
			}
		}
		function getFConfig($att)
		{
			$config = Mage::getStoreConfig('newproduct');
			if (isset($config['newproduct_config']) ) {
				$value = $config['newproduct_config'][$att];
				return $value;
			} else {
				throw new Exception($att.' value not set');
			}
		}
	?>
<?php if(getFConfig('enabled')){ // start enable module?> 
	<?php $_productCollection=$this->getLoadedProductCollection() ?>
	<div class="ma-featured-products">  <!-- start mt products list -->
		<?php if(getFConfig('title')){?>
			<div class="ma-featured-product-title"><h2><?php echo getFConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> <!-- start if exist product -->
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php else: ?>
			<div class="category-products">
			    <?php $_collectionSize = $_productCollection->count() ?>
			    <?php if( !getFConfig('items') ) { $_columnCount = 1 ; } else { $_columnCount = getFConfig('items'); }?>
			    <?php $i=0; foreach ($_productCollection as $_product): ?>
			        <?php if ( $i++ % $_columnCount==0): ?>
			        <ul class="products-grid <?php if( $i == 1 ) echo ' first';?>">
			        <?php endif ?>
			        	<?php 
			        		if ( !getFConfig('width') ){
			        			$w=135;
			        		} else {
			        			$w = getFConfig('width');
			        		}
			        		if( !getFConfig('height') ){
			        			$h=135;
							 }
			        		else {
			        			$h = getFConfig('height');
			        		}
			        	?>
			            <li class="item span6<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<div class="item-inner">
			                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->
					helper('catalog/image')->init($_product, 'small_image')->resize($w,$h); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
			                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
			                <?php if ( getFConfig('review') ): ?>
			                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
			                <?php endif; ?>
			                <?php echo $this->getPriceHtml($_product, true) ?>
			                <div class="actions">
			                	<?php if (getFConfig('addtocart')) { ?>
									<?php if($_product->isSaleable()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
			                    <?php }?>
			                    <?php if( getFConfig('addtowishlist') || getFConfig('addtocompare')){?>
									<ul class="add-to-links">
										<?php if( getFConfig('addtowishlist')){?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php } ?>
										<?php if( getFConfig('addtocompare') ){?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
										<?php }?>
									</ul>
			                    <?php }?>
			                </div>
			                <?php if( getFConfig('description')){?>
			                <div class="ma-desc">
			                	<?php if(!getFConfig('maxlength')){?>
			                    	<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
			                    <?php } else {?>
			                    	<?php echo nl2br(cut_string($this->htmlEscape($_product->getShortDescription()),getFConfig('maxlength'))) ?>			            
			                    <?php }?>			                    
			                </div>
			                <?php }?>
					</div>
			            </li>
			        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			        </ul>
		        <?php endif ?> <!--  -->
		        <?php endforeach ?>
		        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>				
			</div>		
		<?php endif; ?> <!-- end exist product -->
	</div> <!-- end products list -->
<?php } ?>


