<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<!-- 
<?php if (count($this->getStores()) > 1): ?>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <?php echo $this->__('Switch Theme') ?> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' class="active"' : '' ?>
            <li <?php echo $_selected ?>>
                <a  href="<?php echo $_lang->getCurrentUrl() ?>"><?php echo $this->htmlEscape($_lang->getName()) ?></a>
            </li>
                
            <?php endforeach; ?>
        </ul>
    </li>
<?php endif; ?>

<script type="text/javascript">
jQuery(function($){
	var bs={
	        versions:function(){
	            var u = navigator.userAgent, app = navigator.appVersion;
	            return {//移动终端浏览器版本信息
	                trident: u.indexOf('Trident') > -1, //IE内核
	                presto: u.indexOf('Presto') > -1, //opera内核
	                webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
	                gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
	                mobile: !!u.match(/AppleWebKit.*Mobile.*/)||!!u.match(/AppleWebKit/), //是否为移动终端
	                ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
	                android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
	                iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
	                iPad: u.indexOf('iPad') > -1, //是否iPad
	                webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
	            };
	        }(),
	        language:(navigator.browserLanguage || navigator.language).toLowerCase()
	    } 
	    if(bs.versions.mobile){
	        if(bs.versions.android||bs.versions.iPhone||bs.versions.iPad||bs.versions.ios){
	            <?php //header('Location: '.Mage::getBaseUrl().'?__store=phone');exit();?>

	        }else{
	            <?php //header('Location: '.Mage::getBaseUrl().'?__store=default');exit;?>
	        }
	    }
});

</script> -->