<table>
	<caption class="month-record">
		本商品累计售出<em class="count"><?php echo rand(500,1000);?></em>件 ，最近一个月成交<em><?php echo rand(0,500);?></em>件
	</caption>
	<colgroup>
		<col class="col-buyer">
		<col class="col-goods">
		<col class="col-price">
		<col class="col-amount">
		<col class="col-chargetime">
		<col class="col-status">
	</colgroup>
	<tbody>
		<tr>
			<th>买家<span class="tb-anonytip">[登录后可见]</span></th>
			<th>宝贝名称</th>
			<th>价格</th>
			<th>购买数量</th>
			<th>成交时间</th>
			<th>状态</th>
		</tr>
		<?php for ($i=0;$i<20;$i++){?>
			<tr>
				<td class="cell-align-l"><?php echo rand(0, 33);?><span class="tb-anonymous">**</span><?php echo chr(mt_rand(33, 126));?> 
				</td>
				<td class="cell-align-l"><?php echo $productname?> <br>
				</td>
				<td></td>
				<td>1</td>
				<td><?php echo date('Y-m-d H:i:s',(time()-rand(1,1000000)))?></td>
				<td>成交</td>
			</tr>
		<?php }?>
	</tbody>
</table>